#ifndef DASHBOARD_HTML_H
#define DASHBOARD_HTML_H

static const char dashboard_html[] =
"<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
"<title>STM32 Control</title>"
"<style>"
":root{color-scheme:dark;--bg:#111318;--panel:#191d24;--panel2:#202631;--ink:#f4f7fb;--muted:#96a0af;--line:#303846;--ok:#35d07f;--warn:#ffcf5a;--bad:#ff5c70;--accent:#52b7ff}"
"*{box-sizing:border-box}body{margin:0;min-height:100vh;font:15px/1.45 Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,\"Segoe UI\",sans-serif;background:radial-gradient(circle at 15% 0,#263241 0,#111318 34%,#0f1116 100%);color:var(--ink)}"
".shell{width:min(1120px,calc(100% - 32px));margin:0 auto;padding:32px 0 44px}.top{display:flex;align-items:flex-end;justify-content:space-between;gap:16px;margin-bottom:22px}.brand{display:flex;align-items:center;gap:14px}.mark{width:46px;height:46px;border-radius:8px;background:linear-gradient(135deg,#52b7ff,#35d07f);box-shadow:0 14px 36px #0008}.eyebrow{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.12em}.title{font-size:clamp(30px,5vw,54px);font-weight:780;letter-spacing:0;margin:0}.status{display:flex;align-items:center;gap:9px;padding:10px 12px;border:1px solid var(--line);border-radius:8px;background:#161a22}.dot{width:10px;height:10px;border-radius:50%;background:var(--warn);box-shadow:0 0 0 4px #ffcf5a20}.dot.ok{background:var(--ok);box-shadow:0 0 0 4px #35d07f22}.dot.bad{background:var(--bad);box-shadow:0 0 0 4px #ff5c7026}"
".grid{display:grid;grid-template-columns:1.15fr .85fr;gap:18px}.panel{background:linear-gradient(180deg,var(--panel),#151922);border:1px solid var(--line);border-radius:8px;padding:18px;box-shadow:0 18px 45px #0007}.panel h2{margin:0 0 14px;font-size:17px;font-weight:720}.outputs{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.tile{background:var(--panel2);border:1px solid var(--line);border-radius:8px;padding:16px;min-height:146px;display:flex;flex-direction:column;justify-content:space-between}.tile-head{display:flex;justify-content:space-between;gap:12px}.pin{color:var(--muted);font-size:12px}.name{font-size:22px;font-weight:760}.state{font-size:12px;color:var(--muted);text-transform:uppercase;letter-spacing:.1em}.switch{appearance:none;width:68px;height:38px;border-radius:999px;border:1px solid #3c4657;background:#2b3240;position:relative;cursor:pointer;transition:.2s}.switch:before{content:\"\";position:absolute;width:30px;height:30px;top:3px;left:4px;border-radius:50%;background:#d9e0eb;transition:.2s;box-shadow:0 5px 12px #0007}.switch:checked{background:linear-gradient(90deg,#2ecf7b,#52b7ff);border-color:#68d7ff}.switch:checked:before{transform:translateX(28px);background:white}.metrics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.metric{border:1px solid var(--line);border-radius:8px;background:#151a22;padding:16px;min-height:118px}.metric .label{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.1em}.metric .value{font-size:32px;font-weight:760;margin-top:12px}.input-pill{display:inline-flex;align-items:center;gap:9px;padding:8px 10px;border-radius:999px;background:#2b3240;color:#dbe5f3}.input-pill.active{background:#123924;color:#bfffd9}.log{height:142px;overflow:auto;border:1px solid var(--line);border-radius:8px;background:#0e1117;padding:12px;color:#c5cfdd;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px}.bar{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:14px;color:var(--muted);font-size:13px}.btn{border:1px solid var(--line);background:#202631;color:var(--ink);border-radius:8px;padding:9px 12px;cursor:pointer}.btn:hover{border-color:#566377}"
"@media(max-width:820px){.top{align-items:flex-start;flex-direction:column}.grid,.outputs,.metrics{grid-template-columns:1fr}.shell{width:min(100% - 22px,680px);padding-top:20px}.title{font-size:34px}}"
"</style></head><body><main class=\"shell\"><section class=\"top\"><div class=\"brand\"><div class=\"mark\"></div><div><div class=\"eyebrow\">STM32 HTTPS dashboard</div><h1 class=\"title\">Device Control</h1></div></div><div class=\"status\"><span id=\"wsDot\" class=\"dot\"></span><span id=\"wsText\">Connecting</span></div></section>"
"<section class=\"grid\"><div class=\"panel\"><h2>Outputs</h2><div class=\"outputs\">"
"<article class=\"tile\"><div class=\"tile-head\"><div><div class=\"pin\">PB4</div><div class=\"name\">Output 0</div></div><input id=\"out0\" class=\"switch\" type=\"checkbox\" aria-label=\"Output 0\"></div><div class=\"state\" id=\"out0State\">Off</div></article>"
"<article class=\"tile\"><div class=\"tile-head\"><div><div class=\"pin\">PA15</div><div class=\"name\">Output 1</div></div><input id=\"out1\" class=\"switch\" type=\"checkbox\" aria-label=\"Output 1\"></div><div class=\"state\" id=\"out1State\">Off</div></article>"
"</div></div><aside class=\"panel\"><h2>Live State</h2><div class=\"metrics\"><div class=\"metric\"><div class=\"label\">Input m_IN_3</div><div class=\"value\"><span id=\"inputPill\" class=\"input-pill\"><span class=\"dot\"></span><span id=\"inputText\">Low</span></span></div></div><div class=\"metric\"><div class=\"label\">Uptime</div><div class=\"value\" id=\"uptime\">0s</div></div></div><div class=\"bar\"><span id=\"updated\">Waiting for data</span><button id=\"refresh\" class=\"btn\">Refresh</button></div></aside></section>"
"<section class=\"panel\" style=\"margin-top:18px\"><h2>Events</h2><div id=\"log\" class=\"log\"></div></section></main>"
"<script>"
"const $=id=>document.getElementById(id);let ws;"
"function fmt(s){s=Math.floor(s||0);const d=Math.floor(s/86400);s%=86400;const h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60);s%=60;return(d?d+'d ':'')+(h?h+'h ':'')+(m?m+'m ':'')+s+'s'}"
"function log(t){const e=$('log');const p=document.createElement('div');p.textContent=new Date().toLocaleTimeString()+'  '+t;e.prepend(p);while(e.children.length>60)e.lastChild.remove()}"
"function render(s){$('out0').checked=!!s.outputs[0].on;$('out1').checked=!!s.outputs[1].on;$('out0State').textContent=s.outputs[0].on?'On':'Off';$('out1State').textContent=s.outputs[1].on?'On':'Off';$('inputText').textContent=s.input.active?'High':'Low';$('inputPill').classList.toggle('active',!!s.input.active);$('uptime').textContent=fmt(s.uptime);$('updated').textContent='Updated '+new Date().toLocaleTimeString()}"
"async function state(){const r=await fetch('/api/state',{cache:'no-store'});render(await r.json())}"
"async function setOut(id,on){if(ws&&ws.readyState===1){ws.send(JSON.stringify({id,on}))}else{await fetch('/api/output',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,on})});state()}}"
"function connect(){ws=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host+'/ws');ws.onopen=()=>{ $('wsDot').className='dot ok';$('wsText').textContent='Live';log('WebSocket connected');ws.send('state')};ws.onmessage=e=>render(JSON.parse(e.data));ws.onclose=()=>{ $('wsDot').className='dot bad';$('wsText').textContent='Offline';setTimeout(connect,1200)};ws.onerror=()=>ws.close()}"
"$('out0').onchange=e=>setOut(0,e.target.checked);$('out1').onchange=e=>setOut(1,e.target.checked);$('refresh').onclick=()=>ws&&ws.readyState===1?ws.send('state'):state();connect();"
"</script></body></html>";

#endif /* DASHBOARD_HTML_H */
