#!/bin/sh
set -eu

ROOT_DIR=${1:-WebRoot}
OUT_FILE=${2:-Application/Src/web_root.c}
MOUNT_PREFIX=${3:-/web_root}

if [ ! -d "$ROOT_DIR" ]; then
  echo "missing web root: $ROOT_DIR" >&2
  exit 1
fi

if ! command -v gzip >/dev/null 2>&1; then
  echo "gzip is required" >&2
  exit 1
fi

if ! command -v xxd >/dev/null 2>&1; then
  echo "xxd is required" >&2
  exit 1
fi

tmp_dir="${TMPDIR:-/tmp}/webroot-pack.$$"
table_file="$tmp_dir/files.table"
list_file="$tmp_dir/files.list"
mkdir -p "$tmp_dir"
trap 'rm -rf "$tmp_dir"' EXIT INT TERM
: > "$table_file"

mtime_of() {
  if stat -f %m "$1" >/dev/null 2>&1; then
    stat -f %m "$1"
  else
    stat -c %Y "$1"
  fi
}

c_string() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

mkdir -p "$(dirname "$OUT_FILE")"

{
  printf '/* Generated by scripts/prepare_webroot.sh. Do not edit manually. */\n'
  printf '#include "mongoose.h"\n\n'
} > "$OUT_FILE"

index=0
find "$ROOT_DIR" -type f ! -name '.DS_Store' | sort > "$list_file"
while IFS= read -r source; do
  rel=${source#"$ROOT_DIR"/}
  gz_file="$tmp_dir/$rel.gz"
  array_name="web_file_$index"
  mtime=$(mtime_of "$source")
  path=$(c_string "$MOUNT_PREFIX/$rel.gz")

  mkdir -p "$(dirname "$gz_file")"
  gzip -cn -9 "$source" > "$gz_file"

  {
    printf 'static const unsigned char %s[] = {\n' "$array_name"
    xxd -i < "$gz_file"
    printf '};\n\n'
  } >> "$OUT_FILE"

  printf '  {"%s", %s, sizeof(%s), %s},\n' "$path" "$array_name" "$array_name" "$mtime" >> "$table_file"
  index=$((index + 1))
done < "$list_file"

{
  printf 'const struct mg_mem_file mg_packed_files[] = {\n'
  cat "$table_file"
  printf '  {NULL, NULL, 0, 0}\n'
  printf '};\n'
} >> "$OUT_FILE"

echo "packed $index web assets into $OUT_FILE"
